#!/bin/env bash
###############################################################################################################################################################################################################
declare -A get
declare -A post
declare -A cookie
###############################################################################################################################################################################################################

function input {
if [[ ! -z ${HTTP_COOKIE} ]];then
  input=$(echo "$HTTP_COOKIE" | tr -cd 'a-zA-Z0-9=[:space:]')
  for i in ${input};do
    cookie[${i%%=*}]=${i##*=}
  done
fi

if [[ ! -z ${QUERY_STRING} ]];then
  input=$(echo "$QUERY_STRING" | tr -cd 'a-zA-Z0-9=&%')
  OLDIFS=$IFS;IFS="&"
  for i in ${input};do
    get[${i%%=*}]=${i##*=}
  done
  IFS=$OLDIFS
fi

if [[ ${REQUEST_METHOD} == "POST" && ${CONTENT_TYPE} == "application/x-www-form-urlencoded" ]];then
  input=$(cat /dev/stdin | tr -cd 'a-zA-Z0-9=&%')
  OLDIFS=$IFS;IFS="&"
  for i in ${input};do
    post[${i%%=*}]=${i##*=}
  done
  IFS=$OLDIFS
fi

if [[ ${REQUEST_METHOD} == "POST" && ${CONTENT_TYPE} == "text/plain" ]];then
  input=$(cat /dev/stdin | tr -cd 'a-zA-Z0-9=[:space:]')
  for i in ${input};do
    post[${i%%=*}]=${i##*=}
  done
fi

if [[ ${REQUEST_METHOD} == "POST" && $(grep "multipart/form-data" <<< ${CONTENT_TYPE}) ]];then
  input=$(cat /dev/stdin)
fi
}
###############################################################################################################################################################################################################
function session {
if [[ -z ${HTTP_COOKIE} ]];then echo -e "Set-Cookie:session=$(date +%s)\r";fi
echo -e "Content-type:text/html\n\n"
}
###############################################################################################################################################################################################################
function header {
echo "
<!DOCTYPE html><html><head>
<title>spareProject...</title>
<meta charset='utf-8'/>
<link rel='stylesheet' type='text/css' href='/default.css'>
</head>
<body>
<div id='panel' class='top'>
<a class='menu left' href='/index.cgi'><h3><b>[index]</b></h3></a>
<a class='menu left' href='/started.cgi'><h3><b>[started]</b></h3></a>
<a class='menu left' href='/database.cgi'><h3><b>[database]</b></h3></a>
<a class='menu right' href=#><h3><b>[$(date)]</b></h3></a>
<a class='menu right' href=/login.cgi><h3><b>[login]</b></h3></a>
<a class='menu right' href=/2fa.cgi><h3><b>[2fa]</b></h3></a>
</div>
<div id='spacer'>a</div>
"
}
function footer { echo "<div id='spacer'>a</div><div id='panel' class='bottom'>Footer</div></body></html>"; }
###############################################################################################################################################################################################################
