#!/bin/env bash
###############################################################################################################################################################################################################
hostname="archiso-"
hostname+=$(date | md5sum | sed 's/...$//')
echo ${hostname} > /proc/sys/kernel/hostname
echo ${hostname} > /etc/hostname
unset hostname
###############################################################################################################################################################################################################
echo 360 > /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_established
mv /root/09-gnupg.rules /etc/udev/rules.d/
umask 077
gpg --homedir /home/user/gnupg --batch --gen-key /etc/gnupg/batch.user
gpg --homedir /home/user/gnupg --output /home/user/user.public --export user
ssh-keygen -t rsa -b 4096 -f "/home/user/ssh/id_rsa" -N ""
ssh-keygen -t rsa -b 4096 -f "/home/user/sshd/ssh_host_rsa_key" -N ""
pkill gpg-agent
chown -R user:group /home/user
chmod -R 700 /home/user
###############################################################################################################################################################################################################
while [[ $(ls /sys/class/net) == "lo" ]];do sleep 1;done
for i in $(ls /sys/class/net);do if [[ ${i} != lo ]];then macchanger -rb ${i};fi;done
###############################################################################################################################################################################################################
