#!/bin/env bash
hostname="archiso-"
hostname+=$(date | md5sum | sed 's/...$//')
echo ${hostname} > /proc/sys/kernel/hostname
echo ${hostname} > /etc/hostname
unset hostname
while [[ $(ls /sys/class/net) == "lo" ]];do sleep 1;done
for i in $(ls /sys/class/net);do if [[ ${i} != lo ]];then macchanger -rb ${i};fi;done
