#!/bin/env bash
###############################################################################################################################################################################################################
hostname="archiso-"
hostname+=$(date | md5sum | sed 's/...$//')
echo ${hostname} > /proc/sys/kernel/hostname
echo ${hostname} > /etc/hostname
unset hostname
###############################################################################################################################################################################################################
echo 360 > /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_established
mv /root/09-gnupg.rules /etc/udev/rules.d/
###############################################################################################################################################################################################################
while [[ $(ls /sys/class/net) == "lo" ]];do sleep 1;done
for i in $(ls /sys/class/net);do 
  if [[ ${i} != lo ]];then macchanger -rb ${i};fi
  if [[ ${i} == wl* ]];then
    iptables -t nat -A POSTROUTING -o ${i} -j MASQUERADE
    iptables -A FORWARD -i ${i} -o container -m conntrack --ctstate ESTABLISHED,RELATED --ctproto tcp -j ACCEPT
    iptables -A FORWARD -i ${i} -o container -m conntrack --ctstate ESTABLISHED,RELATED --ctproto udp -j ACCEPT
    iptables -A FORWARD -i ${i} -o proxy -m conntrack --ctstate ESTABLISHED,RELATED --ctproto tcp -j ACCEPT
    iptables -A FORWARD -i ${i} -o proxy -m conntrack --ctstate ESTABLISHED,RELATED --ctproto udp -j ACCEPT
    iptables -A FORWARD -p tcp -i container -o ${i} -j ACCEPT
    iptables -A FORWARD -p udp -i container -o ${i} -j ACCEPT
    iptables -A FORWARD -p tcp -i proxy -o ${i} -j ACCEPT
    iptables -A FORWARD -p udp -i proxy -o ${i} -j ACCEPT
  fi
done
###############################################################################################################################################################################################################
